server:
  port: 9091
#  ssl:
#    key-store: classpath:mykeys.jks
#    key-store-password: G4s7Zd6h2
#    key-password: G4s7Zd6h2
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testing_system
    username: testing_connection
    password: G4s7Zd6h2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      #ddl-auto: create/validate/update
  data:
    rest:
      base-path: /api
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9093/oauth2/jwks
  artemis:
    mode: native
#    broker-url: "tcp://192.168.1.210:9876"
    user: "gmak"
    password: "G4s7Zd6h2"
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
  file:
    name: my.log
  logback:
    rollingpolicy:
      max-history: 1


#    add jpa:hibernate:ddl-auto=none in application.properties
#    this sql will be executed